# Week 1 Lab Assignments

You are required to implement the following functions:
- `homogenous_transform_2D` - Perform homogenous transformations for a 2D system
- `homogenous_transform_3D` - Perform homogenous transformations for a 3D system
- `chain_transforms` - Perform a chain of 3D transformations in the given order


In [1]:
# import required libraries
import numpy as np
import matplotlib.pyplot as plt
# To render plots inline
%matplotlib inline

# For unit tests
from tester import LabTester
lab_tester = LabTester()

In [2]:
# Homogenous 2D Transformation
def homogenous_transform_2D(V:np.ndarray, U:np.ndarray, theta:float) -> np.ndarray:
    """
    Input:
        V       - initial vector
        U       - translation vector
        theta   - angle in degrees
    Output: resulting coordinates after rotating V by theta and translating by U
    """

    # Your code here

    pass

## Lab 1: Homogeneous Transformation in 2D
- *Theory*: Translating and rotating a point using homogeneous transformations.
- *Task*: Implement a function that applies a 2D homogeneous transformation matrix to a given point.
- *Expected Output*: Given a vector $(1,0)$ applying a translation of $(3,4)$ and a $\theta = 45°$ rotation, the transformed point should be $(3.707, 4.707)$

In [3]:
lab_tester.test_homogeneous_transform_2d(homogenous_transform_2D)


=== Testing 2D Homogeneous Transformation Implementation ===


TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

In [4]:
# Homogenous 3D Transformation
def homogenous_transform_3D(V:np.ndarray, U:np.ndarray, theta:dict) -> np.ndarray:
    """
    Input:
        V       - initial vector
        U       - translation vector
        theta   - dictionary of angles with the 'x', 'y' and 'z' angles
    Output: resulting coordinates after rotating V by theta and translating by U
    """

    # Your code here
    pass


## Lab 4: Homogeneous Transformation in 3D
- *Theory*: Extending 2D transformations to 3D space.
- *Task*: Implement a function that applies a 3D transformation matrix to a point in 3D.
- *Expected Output*: Given a vector $(2,3,4)$ appying a translation of $(5,5,5)$ and a rotation of $\theta = 90°$ about the z-axis the transformed point should be $(2,7,9)$.

In [7]:
lab_tester.test_homogeneous_transform_3d(homogenous_transform_3D)


=== Testing 3D Homogeneous Transformation Implementation ===
L: 
[2. 7. 9.]
✅ Combined 3D transform: translation(5,5,5) + rotation(90° about z)
L: 
[5. 7. 9.]
✅ Pure 3D translation: no rotation
L: 
[1.000000e+00 6.123234e-17 1.000000e+00]
✅ Pure rotation about x-axis
L: 
[3.74939946e-33 1.22464680e-16 1.00000000e+00]
✅ Combined rotations about x, y, and z axes
L: 
[ 2.00000000e+00 -3.00000000e+00  2.22044605e-16]
✅ Rotations with Negative Translation
L: 
[-2.  6.  1.]
✅ Rotations by odd angles with Translation
L: 
[2. 2. 3.]
✅ Identity transformation
L: 
[ 3.66506351 -2.23205081  0.6160254 ]
✅ Large rotations


## Lab 5: Chain Transformations
- *Theory*: Combining multiple transformations using matrix multiplication.
- *Task*: Implement a function that applies multiple homogeneous transformations sequentially.
- *Expected Output*: Given a sequence of rotations and translations, compute the final transformed position.

In [6]:
# Chain transformations
def chain_transforms(V:np.ndarray, transforms:list) -> np.ndarray:
    """
    Input:
        V           - initial vector
        transforms  - list of 'translation' and 'rotation' - ex:{'translation': np.array([0, 0, 0]), 'rotation': {'z': 0}}
    Output: resulting coordinates after appyling the transforms in the given order
    """

    # Your code here

    pass
    

In [7]:
lab_tester.test_chain_transformations(chain_transforms)


=== Testing Chain Transformations Implementation ===


TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

In [5]:
# Summary of test results
lab_tester.print_summary()


=== Test Summary ===
Passed: 0/1 tests
❌ 1 tests failed
